"""
Cybercrime complaint template generator for Kavach 2.0.

Generates pre-filled complaint text compatible with cybercrime.gov.in
format, including incident details, scam type, amount, and victim statement.
"""

from datetime import datetime, timezone
from typing import Optional

from app.models.session import ConversationSession
from app.models.user import User
from app.models.transaction import Transaction


def generate_complaint(
    session: ConversationSession,
    user: User,
    transaction: Transaction,
) -> str:
    """
    Generate a pre-filled cybercrime.gov.in complaint in plain text.

    The complaint includes incident date/time, description of scam type,
    amount attempted, scammer contact if known, and victim statement.

    Args:
        session: Conversation session with message history.
        user: User profile details.
        transaction: The flagged transaction.

    Returns:
        Formatted complaint text ready for submission.
    """
    now = datetime.now(timezone.utc)
    incident_time = transaction.initiated_at or now

    # Determine scam type from session risk level and messages
    scam_type = _determine_scam_type(session)

    # Build complaint text
    complaint = f"""
=====================================
CYBERCRIME COMPLAINT - KAVACH 2.0
(For submission at cybercrime.gov.in)
=====================================

COMPLAINT CATEGORY: Financial Fraud / Online Fraud
SUB-CATEGORY: {scam_type}

--- COMPLAINANT DETAILS ---
Name: {user.name or "Not Provided"}
Phone: {user.phone}
Language: {user.language_preference}

--- INCIDENT DETAILS ---
Date of Incident: {incident_time.strftime("%d/%m/%Y")}
Time of Incident: {incident_time.strftime("%H:%M IST")}
Platform: UPI / WhatsApp

--- TRANSACTION DETAILS ---
Amount (Attempted): INR {transaction.amount:,.2f}
Recipient Account/UPI ID: {transaction.recipient_phone}
Transaction Status: {transaction.status}
Risk Score: {session.risk_score}/100

--- SCAMMER DETAILS ---
Scammer Contact: {transaction.recipient_phone}
Mode of Contact: Phone Call / WhatsApp Message

--- INCIDENT DESCRIPTION ---
{_generate_incident_description(session, transaction, scam_type)}

--- VICTIM STATEMENT ---
I, {user.name or "[Name]"}, residing at [Address], hereby declare that
I was targeted by an online fraud attempt on {incident_time.strftime("%d/%m/%Y")}.
The scammer contacted me and attempted to defraud me of INR {transaction.amount:,.2f}.
Kavach 2.0 fraud detection system intercepted this transaction and alerted me
before the transfer was completed.

I request the authorities to investigate this matter and take necessary action
against the scammer(s) involved.

--- EVIDENCE ---
- Kavach 2.0 conversation log (attached)
- Transaction attempt details (above)
- Risk assessment score: {session.risk_score}/100

--- IMPORTANT HELPLINES ---
National Cybercrime Helpline: 1930
Cybercrime Portal: https://cybercrime.gov.in
RBI Ombudsman: https://cms.rbi.org.in

=====================================
Generated by Kavach 2.0 on {now.strftime("%d/%m/%Y at %H:%M UTC")}
This is an auto-generated template. Please verify all details before submission.
=====================================
""".strip()

    return complaint


def _determine_scam_type(session: ConversationSession) -> str:
    """
    Determine the scam type from session context.

    Args:
        session: Conversation session with messages.

    Returns:
        Human-readable scam type string.
    """
    messages_text = " ".join(
        msg.get("content", "") for msg in (session.messages or [])
    ).lower()

    if any(w in messages_text for w in ["arrest", "digital arrest", "cbi", "police"]):
        return "Digital Arrest Scam"
    if any(w in messages_text for w in ["kyc", "aadhaar", "aadhar", "pan"]):
        return "KYC / Aadhaar Fraud"
    if any(w in messages_text for w in ["lottery", "prize", "winner"]):
        return "Lottery / Prize Scam"
    if any(w in messages_text for w in ["job", "offer", "work from home"]):
        return "Fake Job Offer Scam"
    if any(w in messages_text for w in ["rbi", "bank", "freeze", "account"]):
        return "Bank Impersonation Fraud"

    return "Online Financial Fraud (Unspecified)"


def _generate_incident_description(
    session: ConversationSession,
    transaction: Transaction,
    scam_type: str,
) -> str:
    """
    Generate a narrative description of the incident.

    Args:
        session: Conversation session.
        transaction: The flagged transaction.
        scam_type: Determined scam type.

    Returns:
        Narrative incident description.
    """
    description = (
        f"On {transaction.initiated_at.strftime('%d/%m/%Y') if transaction.initiated_at else 'the reported date'}, "
        f"I received communication from an unknown person/entity. "
        f"The scam type has been identified as: {scam_type}.\n\n"
        f"The scammer attempted to convince me to transfer INR {transaction.amount:,.2f} "
        f"to the account/UPI ID: {transaction.recipient_phone}.\n\n"
        f"The Kavach 2.0 fraud detection system identified this transaction as "
        f"HIGH RISK (score: {session.risk_score}/100) and intervened by alerting me "
        f"and my trusted contact about the potential fraud.\n\n"
        f"Total number of messages exchanged during this incident: "
        f"{session.get_message_count()}"
    )
    return description


def generate_recovery_guide(language: str) -> list[str]:
    """
    Generate step-by-step recovery guide.

    Args:
        language: Language code for the guide.

    Returns:
        List of recovery steps in the specified language.
    """
    guides: dict[str, list[str]] = {
        "hi": [
            "🚫 अभी और कोई पैसा ट्रांसफर न करें",
            "📞 तुरंत 1930 (साइबर क्राइम हेल्पलाइन) पर कॉल करें",
            "🌐 cybercrime.gov.in पर शिकायत दर्ज करें",
            "🏦 अपने बैंक को सूचित करें — ट्रांजैक्शन freeze/flag करवाएं",
            "📸 स्कैमर के सभी messages और calls का screenshot लें",
            "👨‍👩‍👧 अपने परिवार के किसी विश्वसनीय सदस्य को बताएं",
        ],
        "te": [
            "🚫 ఇప్పుడు ఇంకా డబ్బు ట్రాన్స్‌ఫర్ చేయకండి",
            "📞 వెంటనే 1930 (సైబర్ క్రైమ్ హెల్ప్‌లైన్) కు కాల్ చేయండి",
            "🌐 cybercrime.gov.in లో ఫిర్యాదు చేయండి",
            "🏦 మీ బ్యాంక్‌కు తెలియజేయండి — లావాదేవీని freeze చేయించండి",
            "📸 స్కామర్ messages మరియు calls స్క్రీన్‌షాట్ తీయండి",
            "👨‍👩‍👧 మీ కుటుంబంలో నమ్మకమైన వ్యక్తికి చెప్పండి",
        ],
        "ta": [
            "🚫 இப்போது மேலும் பணம் அனுப்ப வேண்டாம்",
            "📞 உடனடியாக 1930 (சைபர் கிரைம் ஹெல்ப்லைன்) அழைக்கவும்",
            "🌐 cybercrime.gov.in இல் புகார் பதிவு செய்யவும்",
            "🏦 உங்கள் வங்கிக்கு தெரிவிக்கவும் — பரிவர்த்தனையை freeze செய்யுங்கள்",
            "📸 மோசடி செய்பவரின் messages மற்றும் calls screenshot எடுக்கவும்",
            "👨‍👩‍👧 உங்கள் குடும்பத்தில் நம்பகமான நபரிடம் சொல்லுங்கள்",
        ],
        "bn": [
            "🚫 এখন আর কোনো টাকা ট্রান্সফার করবেন না",
            "📞 এখনই 1930 (সাইবার ক্রাইম হেল্পলাইন) এ কল করুন",
            "🌐 cybercrime.gov.in এ অভিযোগ দায়ের করুন",
            "🏦 আপনার ব্যাংককে জানান — লেনদেন freeze করান",
            "📸 স্ক্যামারের সব messages ও calls এর screenshot নিন",
            "👨‍👩‍👧 আপনার পরিবারের বিশ্বস্ত সদস্যকে জানান",
        ],
        "en": [
            "🚫 Don't transfer any more money right now",
            "📞 Call 1930 (National Cybercrime Helpline) immediately",
            "🌐 File a complaint at cybercrime.gov.in",
            "🏦 Inform your bank — request them to freeze/flag the transaction",
            "📸 Screenshot all messages and calls from the scammer",
            "👨‍👩‍👧 Tell a trusted family member about this incident",
        ],
    }

    return guides.get(language, guides["en"])


def generate_helpline_message(language: str) -> str:
    """
    Generate 1930 helpline instruction message.

    Args:
        language: Language code.

    Returns:
        Helpline instructions in the specified language.
    """
    messages: dict[str, str] = {
        "hi": (
            "📞 *राष्ट्रीय साइबर क्राइम हेल्पलाइन: 1930*\n\n"
            "• यह 24x7 उपलब्ध है\n"
            "• अपना मोबाइल नंबर और ट्रांजैक्शन details तैयार रखें\n"
            "• शांत रहें और सभी जानकारी clearly बताएं\n"
            "• Complaint number नोट करें\n\n"
            "🌐 ऑनलाइन शिकायत: https://cybercrime.gov.in"
        ),
        "te": (
            "📞 *జాతీయ సైబర్ క్రైమ్ హెల్ప్‌లైన్: 1930*\n\n"
            "• 24x7 అందుబాటులో ఉంది\n"
            "• మీ మొబైల్ నంబర్ మరియు transaction details సిద్ధంగా ఉంచండి\n"
            "• ప్రశాంతంగా ఉండండి మరియు అన్ని సమాచారం స్పష్టంగా చెప్పండి\n"
            "• Complaint number నోట్ చేయండి\n\n"
            "🌐 ఆన్‌లైన్ ఫిర్యాదు: https://cybercrime.gov.in"
        ),
        "ta": (
            "📞 *தேசிய சைபர் கிரைம் ஹெல்ப்லைன்: 1930*\n\n"
            "• 24x7 கிடைக்கும்\n"
            "• உங்கள் மொபைல் எண் மற்றும் transaction details தயாராக வைக்கவும்\n"
            "• அமைதியாக இருங்கள் மற்றும் அனைத்து தகவல்களையும் தெளிவாக சொல்லுங்கள்\n"
            "• Complaint number குறித்துக்கொள்ளுங்கள்\n\n"
            "🌐 ஆன்லைன் புகார்: https://cybercrime.gov.in"
        ),
        "bn": (
            "📞 *জাতীয় সাইবার ক্রাইম হেল্পলাইন: 1930*\n\n"
            "• ২৪x৭ পাওয়া যায়\n"
            "• আপনার মোবাইল নম্বর ও transaction details প্রস্তুত রাখুন\n"
            "• শান্ত থাকুন এবং সব তথ্য স্পষ্টভাবে জানান\n"
            "• Complaint number নোট করুন\n\n"
            "🌐 অনলাইন অভিযোগ: https://cybercrime.gov.in"
        ),
        "en": (
            "📞 *National Cybercrime Helpline: 1930*\n\n"
            "• Available 24x7\n"
            "• Keep your mobile number and transaction details ready\n"
            "• Stay calm and explain all details clearly\n"
            "• Note down the complaint number\n\n"
            "🌐 Online complaint: https://cybercrime.gov.in"
        ),
    }

    return messages.get(language, messages["en"])
